apiVersion: v1
kind: Service
metadata:
  name: gateway-headless
  namespace: mercury
spec:
  clusterIP: None
  selector:
    app: gateway
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: http
      port: 4000
      targetPort: 4000
