// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xb7c5f0e1a2d3f4e5n;
/**
* Outer wire format — routing info only, no plaintext content.
* Server reads this to route; inner payload is E2EE.
*
*/
export class Envelope extends $.Struct {
  static readonly _capnp = {
    displayName: "Envelope",
    id: "ccbef924553f6fc6",
    size: new $.ObjectSize(8, 5),
  };
  _adoptTenantId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownTenantId(): $.Orphan<$.Data> {
    return $.utils.disown(this.tenantId);
  }
  /**
* 16 bytes UUID
*
*/
  get tenantId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasTenantId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initTenantId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set tenantId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptChannelId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownChannelId(): $.Orphan<$.Data> {
    return $.utils.disown(this.channelId);
  }
  /**
* 16 bytes UUID
*
*/
  get channelId(): $.Data {
    return $.utils.getData(1, this);
  }
  _hasChannelId(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initChannelId(length: number): $.Data {
    return $.utils.initData(1, length, this);
  }
  set channelId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  _adoptSenderId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownSenderId(): $.Orphan<$.Data> {
    return $.utils.disown(this.senderId);
  }
  /**
* 16 bytes UUID (cleared by sealed sender)
*
*/
  get senderId(): $.Data {
    return $.utils.getData(2, this);
  }
  _hasSenderId(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initSenderId(length: number): $.Data {
    return $.utils.initData(2, length, this);
  }
  set senderId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  _adoptMessageId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownMessageId(): $.Orphan<$.Data> {
    return $.utils.disown(this.messageId);
  }
  /**
* 16 bytes ULID
*
*/
  get messageId(): $.Data {
    return $.utils.getData(3, this);
  }
  _hasMessageId(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initMessageId(length: number): $.Data {
    return $.utils.initData(3, length, this);
  }
  set messageId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  /**
* Unix millis
*
*/
  get timestamp(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestamp(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  _adoptPayload(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownPayload(): $.Orphan<$.Data> {
    return $.utils.disown(this.payload);
  }
  /**
* Encrypted MLS ciphertext (opaque to server)
*
*/
  get payload(): $.Data {
    return $.utils.getData(4, this);
  }
  _hasPayload(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initPayload(length: number): $.Data {
    return $.utils.initData(4, length, this);
  }
  set payload(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  toString(): string { return "Envelope_" + super.toString(); }
}
