// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xf1e2d3c4b5a69788n;
export class TypingEvent extends $.Struct {
  static readonly _capnp = {
    displayName: "TypingEvent",
    id: "fd0ff644517e5058",
    size: new $.ObjectSize(0, 1),
  };
  _adoptUserId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownUserId(): $.Orphan<$.Data> {
    return $.utils.disown(this.userId);
  }
  /**
* 16 bytes UUID
*
*/
  get userId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasUserId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initUserId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set userId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "TypingEvent_" + super.toString(); }
}
export class ReadReceipt extends $.Struct {
  static readonly _capnp = {
    displayName: "ReadReceipt",
    id: "d5e46a43a3493309",
    size: new $.ObjectSize(0, 2),
  };
  _adoptUserId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownUserId(): $.Orphan<$.Data> {
    return $.utils.disown(this.userId);
  }
  /**
* 16 bytes UUID
*
*/
  get userId(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasUserId(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initUserId(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set userId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptMessageId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownMessageId(): $.Orphan<$.Data> {
    return $.utils.disown(this.messageId);
  }
  /**
* 16 bytes ULID
*
*/
  get messageId(): $.Data {
    return $.utils.getData(1, this);
  }
  _hasMessageId(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initMessageId(length: number): $.Data {
    return $.utils.initData(1, length, this);
  }
  set messageId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  toString(): string { return "ReadReceipt_" + super.toString(); }
}
export class MlsKeyPackage extends $.Struct {
  static readonly _capnp = {
    displayName: "MlsKeyPackage",
    id: "e9ca7a543cf3ec3b",
    size: new $.ObjectSize(0, 1),
  };
  _adoptKeyPackage(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownKeyPackage(): $.Orphan<$.Data> {
    return $.utils.disown(this.keyPackage);
  }
  /**
* Opaque MLS KeyPackage bytes
*
*/
  get keyPackage(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasKeyPackage(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initKeyPackage(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set keyPackage(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "MlsKeyPackage_" + super.toString(); }
}
export class MlsKeyPackageList extends $.Struct {
  static readonly _capnp = {
    displayName: "MlsKeyPackageList",
    id: "944950149dc4c616",
    size: new $.ObjectSize(0, 1),
  };
  _adoptKeyPackages(value: $.Orphan<$.List<$.Data>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownKeyPackages(): $.Orphan<$.List<$.Data>> {
    return $.utils.disown(this.keyPackages);
  }
  /**
* List of opaque KeyPackage bytes
*
*/
  get keyPackages(): $.List<$.Data> {
    return $.utils.getList(0, $.DataList, this);
  }
  _hasKeyPackages(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initKeyPackages(length: number): $.List<$.Data> {
    return $.utils.initList(0, $.DataList, length, this);
  }
  set keyPackages(value: $.List<$.Data>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "MlsKeyPackageList_" + super.toString(); }
}
export class MlsCommit extends $.Struct {
  static readonly _capnp = {
    displayName: "MlsCommit",
    id: "d19a5b65e6669025",
    size: new $.ObjectSize(0, 1),
  };
  _adoptCommit(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownCommit(): $.Orphan<$.Data> {
    return $.utils.disown(this.commit);
  }
  /**
* Opaque MLS Commit bytes
*
*/
  get commit(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasCommit(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initCommit(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set commit(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "MlsCommit_" + super.toString(); }
}
export class MlsWelcome extends $.Struct {
  static readonly _capnp = {
    displayName: "MlsWelcome",
    id: "d74f7391ba94c599",
    size: new $.ObjectSize(0, 2),
  };
  _adoptWelcome(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownWelcome(): $.Orphan<$.Data> {
    return $.utils.disown(this.welcome);
  }
  /**
* Opaque MLS Welcome bytes
*
*/
  get welcome(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasWelcome(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initWelcome(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set welcome(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptUserId(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownUserId(): $.Orphan<$.Data> {
    return $.utils.disown(this.userId);
  }
  /**
* 16 bytes — target user
*
*/
  get userId(): $.Data {
    return $.utils.getData(1, this);
  }
  _hasUserId(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initUserId(length: number): $.Data {
    return $.utils.initData(1, length, this);
  }
  set userId(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  toString(): string { return "MlsWelcome_" + super.toString(); }
}
